# Generated by Django 3.1.7 on 2021-03-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210329_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='listing',
            name='actual_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
